

export const FORM_START = 'FORM_START';
export const FORM_SUCCESS = 'FORM_SUCCESS';
export const FORM_FAILED = 'FORM_FAILED';


export const SET_IMAGE_URL = 'SET_IMAGE_URL';


export const FACE_ANALYZE_START = 'FACE_ANALYZE_START';
export const FACE_ANALYZE_SUCCESS = 'FACE_ANALYZE_SUCCESS';
export const FACE_ANALYZE_FAILED = 'FACE_ANALYZE_FAILED';




export const IMAGE_UPLOAD_START = 'IMAGE_UPLOAD_START';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILED = 'IMAGE_UPLOAD_FAILED';
export const IMAGE_UPLOAD_PROGRESS = 'IMAGE_UPLOAD_PROGRESS';


export const UPDATE_DATA = 'UPDATE_DATA';


export const VERIFY_TOKEN_START = 'VERIFY_TOKEN_START';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAILED = 'VERIFY_TOKEN_FAILED';


export const GET_PROFILE_DATA_START = 'GET_PROFILE_DATA_START';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILED = 'GET_PROFILE_DATA_FAILED';